### ISSUE TITLE
Form not connected after provided with the GH access token

### ISSUE THREAD

**Issue by EdinK1** [shwilliam/gister#4]
<img width="553" alt="Screen Shot 2019-10-10 at 6 25 16 PM" src="https://user-images.githubusercontent.com/38442554/66617796-6ccf0980-eb8b-11e9-8992-1a50e30da406.png">

**Comment by shwilliam** [comment]
I believe it is safe to ignore this warning for now as any GH api calls require your token. It also should not appear once the app has been packaged.

**Comment by shwilliam** [comment]
Closing this for now. Feel free to comment if this seems to have any impact on features/security.
